# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CambiarContra.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NuevaContra(QtWidgets.QMainWindow):
    def setupUi(self, NuevaContra):
        NuevaContra.setObjectName("NuevaContra")
        NuevaContra.resize(365, 253)
        NuevaContra.setStyleSheet("background-color: rgb(20, 18, 35);")
        self.centralwidget = QtWidgets.QWidget(NuevaContra)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton.setStyleSheet("border-image: url(:/regresar/Downloads/flecha-hacia-atras.png);\n"
"background-color: rgb(35, 134, 54);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 160, 291, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 200, 151, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(35, 134, 54);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 130, 211, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 301, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 181, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 90, 291, 25))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.label_5.setStyleSheet("border-image: url(:/regresar/Downloads/candado.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 41, 41))
        self.label_6.setStyleSheet("border-image: url(:/regresar/Downloads/candado.png);")
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        NuevaContra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NuevaContra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 22))
        self.menubar.setObjectName("menubar")
        NuevaContra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NuevaContra)
        self.statusbar.setObjectName("statusbar")
        NuevaContra.setStatusBar(self.statusbar)

        self.retranslateUi(NuevaContra)
        QtCore.QMetaObject.connectSlotsByName(NuevaContra)

    def retranslateUi(self, NuevaContra):
        _translate = QtCore.QCoreApplication.translate
        NuevaContra.setWindowTitle(_translate("NuevaContra", "MainWindow"))
        self.pushButton_2.setText(_translate("NuevaContra", "Cambiar contraseña"))
        self.label.setText(_translate("NuevaContra", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Confirmar contraseña:</span></p></body></html>"))
        self.label_2.setText(_translate("NuevaContra", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">¿Olvidaste tu contraseña?</span></p></body></html>"))
        self.label_4.setText(_translate("NuevaContra", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Nueva contraseña:</span></p></body></html>"))
        self.label_5.setText(_translate("NuevaContra", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("NuevaContra", "<html><head/><body><p><br/></p></body></html>"))

import IconosCOntraseña


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NuevaContra = QtWidgets.QMainWindow()
    ui = Ui_NuevaContra()
    ui.setupUi(NuevaContra)
    NuevaContra.show()
    sys.exit(app.exec_())
