# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContraNueva.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NuevaContra(QtWidgets.QMainWindow):
    def setupUi(self, ConfimarContra):
        ConfimarContra.setObjectName("ConfimarContra")
        ConfimarContra.resize(402, 266)
        ConfimarContra.setStyleSheet("background-color: rgb(20, 18, 35);")
        self.centralwidget = QtWidgets.QWidget(ConfimarContra)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton.setStyleSheet("border-image: url(:/regresar/Downloads/flecha-hacia-atras.png);\n"
"background-color: rgb(35, 134, 54);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 170, 291, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 210, 91, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(35, 134, 54);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 301, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.label_3.setStyleSheet("border-image: url(:/regresar/Downloads/bloquear.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 70, 201, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 100, 291, 25))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.label_5.setStyleSheet("border-image: url(:/regresar/Downloads/candado.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 51, 51))
        self.label_6.setStyleSheet("border-image: url(:/regresar/Downloads/candado.png);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 140, 231, 21))
        self.label_7.setObjectName("label_7")
        ConfimarContra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfimarContra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 22))
        self.menubar.setObjectName("menubar")
        ConfimarContra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfimarContra)
        self.statusbar.setObjectName("statusbar")
        ConfimarContra.setStatusBar(self.statusbar)

        self.retranslateUi(ConfimarContra)
        QtCore.QMetaObject.connectSlotsByName(ConfimarContra)

    def retranslateUi(self, ConfimarContra):
        _translate = QtCore.QCoreApplication.translate
        ConfimarContra.setWindowTitle(_translate("ConfimarContra", "MainWindow"))
        self.pushButton_2.setText(_translate("ConfimarContra", "Confirmar"))
        self.label_2.setText(_translate("ConfimarContra", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">¿Olvidaste tu contraseña?</span></p></body></html>"))
        self.label_4.setText(_translate("ConfimarContra", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Nueva contraseña:</span></p></body></html>"))
        self.label_5.setText(_translate("ConfimarContra", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("ConfimarContra", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("ConfimarContra", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Confirmar contraseña:</span></p></body></html>"))
import CambiarContra


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfimarContra = QtWidgets.QMainWindow()
    ui = Ui_NuevaContra()
    ui.setupUi(ConfimarContra)
    ConfimarContra.show()
    sys.exit(app.exec_())
