# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EspecificacionesEtapas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from Datos.dtEtapa import DT_etapa


class Ui_Especificaciones_Etapas(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("background-color: rgb(20, 18, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 70, 131, 41))
        self.label.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 80, 121, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 70, 121, 41))
        self.label_2.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 80, 121, 25))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 70, 191, 41))
        self.label_3.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(820, 80, 121, 25))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 10, 541, 41))
        self.label_5.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 89, 25))
        self.pushButton.setStyleSheet("\n"
                                      "background-color: rgb(35, 134, 54)")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 140, 971, 391))
        self.tableWidget.setStyleSheet("background-color: rgb(224, 224, 224);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Nombre:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Número:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Presupuesto:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Especificaciones de las etapas</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Volver"))
    def cargar_etapa(self):
        etapas = DT_etapa.listarEtapa()
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(len(etapas))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderLabels(
            ["ID etapa", "ID proyecto", "Nombre", "Descripcion", "Presupuesto", "Numero de etapa"])
        self.tableWidget.setColumnWidth(0, 157)
        self.tableWidget.setColumnWidth(1, 150)
        self.tableWidget.setColumnWidth(2, 250)
        self.tableWidget.setColumnWidth(3, 300)
        self.tableWidget.setColumnWidth(4, 250)
        self.tableWidget.setColumnWidth(5, 168)
        self.tableWidget.setColumnHidden(0, True)
        self.tableWidget.setColumnHidden(1, True)
        for i, etapa in enumerate(etapas):
            self.tableWidget.setItem(i, 0, QTableWidgetItem(str(etapas.idEtapa)))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(str(etapas.idProyecto)))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(str(etapas.nombreEtapa)))
            self.tableWidget.setItem(i, 3, QTableWidgetItem(str(etapas.descripcion)))
            self.tableWidget.setItem(i, 4, QTableWidgetItem(str(etapas.presupuestoEtapa)))
            self.tableWidget.setItem(i, 5, QTableWidgetItem(str(etapas.NumEtapa)))

        alignment = QtCore.Qt.AlignCenter

        for i in range(self.tableWidget.columnCount()):
            for j in range(self.tableWidget.rowCount()):
                item = self.tableWidget.item(j, i)
                if item is not None:
                    item.setTextAlignment(alignment)


import logo1
import logos2

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Especificaciones_Etapas()
    ui.setupUi(MainWindow)
    ui.cargar_etapa()
    MainWindow.show()
    sys.exit(app.exec_())
