# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreguntarUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsuarioRecuperar(QtWidgets.QMainWindow):
    def setupUi(self, UsuarioRecuperar):
        UsuarioRecuperar.setObjectName("UsuarioRecuperar")
        UsuarioRecuperar.resize(334, 158)
        UsuarioRecuperar.setStyleSheet("background-color: rgb(20, 18, 35);")
        self.centralwidget = QtWidgets.QWidget(UsuarioRecuperar)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton.setStyleSheet("border-image: url(:/regresar/Downloads/flecha-hacia-atras.png);\n"
"background-color: rgb(35, 134, 54);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 70, 201, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 110, 61, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(35, 134, 54);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 51, 51))
        self.label_3.setStyleSheet("border-image: url(:/regresar/Downloads/perfil.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        UsuarioRecuperar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UsuarioRecuperar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 334, 22))
        self.menubar.setObjectName("menubar")
        UsuarioRecuperar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UsuarioRecuperar)
        self.statusbar.setObjectName("statusbar")
        UsuarioRecuperar.setStatusBar(self.statusbar)

        self.retranslateUi(UsuarioRecuperar)
        QtCore.QMetaObject.connectSlotsByName(UsuarioRecuperar)

    def retranslateUi(self, UsuarioRecuperar):
        _translate = QtCore.QCoreApplication.translate
        UsuarioRecuperar.setWindowTitle(_translate("UsuarioRecuperar", "MainWindow"))
        self.pushButton_2.setText(_translate("UsuarioRecuperar", "Buscar"))
        self.label.setText(_translate("UsuarioRecuperar", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Usuario:</span></p></body></html>"))
        self.label_2.setText(_translate("UsuarioRecuperar", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Recuperar cuenta</span></p></body></html>"))
import IconosCOntraseña


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsuarioRecuperar = QtWidgets.QMainWindow()
    ui = Ui_UsuarioRecuperar()
    ui.setupUi(UsuarioRecuperar)
    UsuarioRecuperar.show()
    sys.exit(app.exec_())
