# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Referencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 586)
        MainWindow.setStyleSheet("background-color: rgb(4, 30, 59);\n"
"font: 75 11pt \"Ubuntu\";\n"
"border-radius: 10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 1031, 41))
        self.label_5.setStyleSheet("font: 75 16pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 89, 25))
        self.pushButton.setStyleSheet("font: 75 11pt \"Ubuntu Bold\";\n"
"background-color: rgb(51, 209, 122);\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 251, 41))
        self.label_7.setStyleSheet("font: 75 14pt \"Ubuntu\";\n"
"background-color: rgb(224, 224, 224);")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 420, 181, 61))
        self.pushButton_2.setStyleSheet("font: 75 11pt \"Ubuntu Bold\";\n"
"background-color: rgb(51, 209, 122);\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 420, 181, 61))
        self.pushButton_3.setStyleSheet("font: 75 11pt \"Ubuntu Bold\";\n"
"background-color: rgb(51, 209, 122);\n"
"border-radius: 10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 140, 451, 41))
        self.label_10.setStyleSheet("background-color: rgb(224, 224, 224);font: 75 11pt \"Ubuntu\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 240, 451, 41))
        self.label_11.setStyleSheet("background-color: rgb(224, 224, 224);\n"
"font: 75 11pt \"Ubuntu\";")
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 200, 281, 41))
        self.label_8.setStyleSheet("font: 75 14pt \"Ubuntu\";background-color: rgb(224, 224, 224);")
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(560, 240, 451, 41))
        self.label_12.setStyleSheet("background-color: rgb(224, 224, 224);font: 75 11pt \"Ubuntu\";")
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 200, 521, 41))
        self.label_9.setStyleSheet("background-color: rgb(224, 224, 224);font: 75 14pt \"Ubuntu\";")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(560, 140, 451, 41))
        self.label_13.setStyleSheet("background-color: rgb(224, 224, 224);font: 75 11pt \"Ubuntu\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(390, 100, 521, 41))
        self.label_14.setStyleSheet("font: 75 14pt \"Ubuntu\";\n"
"background-color: rgb(224, 224, 224);")
        self.label_14.setObjectName("label_14")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 1001, 221))
        self.groupBox.setStyleSheet("background-color: rgb(224, 224, 224);\n"
"font: 75 20pt \"Ubuntu Bold\";")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 1001, 211))
        self.groupBox_2.setStyleSheet("background-color: rgb(224, 224, 224);\n"
"font: 75 20pt \"Ubuntu Bold\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 1001, 81))
        self.label_6.setStyleSheet("font: 75 11pt \"Ubuntu\";\n"
"background-color: rgb(168, 168, 168);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.label_7.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_8.raise_()
        self.label_12.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Se ha encontrado una referencia!</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Volver"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Nombre guardado:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Nombre guardado"))
        self.pushButton_3.setText(_translate("MainWindow", "Nombre actual"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">1234567891011121314151619202122232425</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">1234567891011121314151619202122232425</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Referencia guardada:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">1234567891011121314151619202122232425</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Referencia actual:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">1234567891011121314151619202122232425</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Nombre actual:</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Datos:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Datos:"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#000000;\">¿DESEA QUEDARSE CON EL NOMBRE ACTUAL O EL GUARDADO?</span></p></body></html>"))
import logo1
import logos2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
