# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificacionEliminacionProyecto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verificarEliminacion(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 380)
        MainWindow.setMinimumSize(QtCore.QSize(520, 380))
        MainWindow.setMaximumSize(QtCore.QSize(520, 380))
        MainWindow.setBaseSize(QtCore.QSize(520, 380))
        MainWindow.setStyleSheet("background-color: rgb(28, 18, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 320, 89, 25))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 320, 89, 25))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 150, 451, 131))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("background-color: transparent;\n"
"color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 91, 91))
        self.label_2.setStyleSheet("border-image: url(:/imagenes/advertencia.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 30, 101, 81))
        self.label_3.setStyleSheet("border-image: url(:/imagenes/proyecto.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eliminar proyecto"))
        self.pushButton.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_2.setText(_translate("MainWindow", "Aceptar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Tenga en cuenta que al eliminar un </span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">proyecto se eliminaran todos los gastos, </span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">etapas y rubros asociados al mismo sin</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">opcion de recuperar esta informacion</span></p></body></html>"))
import verificareliminacion

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_verificarEliminacion()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())